/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{tsx,scss}"],
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",
        primary: {
          DEFAULT: "hsl(var(--color-primary) / <alpha-value>)",
          50: "hsl(var(--color-primary-50) / <alpha-value>)",
          100: "hsl(var(--color-primary-100) / <alpha-value>)",
          200: "hsl(var(--color-primary-200) / <alpha-value>)",
          300: "hsl(var(--color-primary-300) / <alpha-value>)",
          400: "hsl(var(--color-primary-400) / <alpha-value>)",
          500: "hsl(var(--color-primary-500) / <alpha-value>)",
          600: "hsl(var(--color-primary-600) / <alpha-value>)",
          700: "hsl(var(--color-primary-700) / <alpha-value>)",
          800: "hsl(var(--color-primary-800) / <alpha-value>)",
          900: "hsl(var(--color-primary-900) / <alpha-value>)",
          950: "hsl(var(--color-primary-950) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "hsl(var(--color-secondary) / <alpha-value>)",
          50: "hsl(var(--color-secondary-50) / <alpha-value>)",
          100: "hsl(var(--color-secondary-100) / <alpha-value>)",
          200: "hsl(var(--color-secondary-200) / <alpha-value>)",
          300: "hsl(var(--color-secondary-300) / <alpha-value>)",
          400: "hsl(var(--color-secondary-400) / <alpha-value>)",
          500: "hsl(var(--color-secondary-500) / <alpha-value>)",
          600: "hsl(var(--color-secondary-600) / <alpha-value>)",
          700: "hsl(var(--color-secondary-700) / <alpha-value>)",
          800: "hsl(var(--color-secondary-800) / <alpha-value>)",
          900: "hsl(var(--color-secondary-900) / <alpha-value>)",
          950: "hsl(var(--color-secondary-950) / <alpha-value>)",
        },
        tertiary: { DEFAULT: "hsl(var(--color-tertiary) / <alpha-value>)" },
        accent: { DEFAULT: "hsl(var(--color-accent) / <alpha-value>)" },
        gray: { DEFAULT: "hsl(var(--color-gray) / <alpha-value>)" },
        red: { DEFAULT: "hsl(var(--color-red) / <alpha-value>)" },
        green: { DEFAULT: "hsl(var(--color-green) / <alpha-value>)" },
        blue: { DEFAULT: "hsl(var(--color-blue) / <alpha-value>)" },
        cyan: { DEFAULT: "hsl(var(--color-cyan) / <alpha-value>)" },
      },
    },
  },
  plugins: [],
};
